### ISSUE TITLE
pip install annofilt error

### ISSUE THREAD

**Issue by yzhzu** [nickp60/annofilt#1]
today when I install annofilt using pip , but the error occurred. can somebody help me? thanks
   pip  install  annofilt
Collecting annofilt
  Using cached annofilt-0.0.2.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/zhuyongzhang/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-93p017l5/annofilt/setup.py'"'"'; __file__='"'"'/tmp/pip-install-93p017l5/annofilt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dpy644mc
         cwd: /tmp/pip-install-93p017l5/annofilt/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-93p017l5/annofilt/setup.py", line 9, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by nickp60** [comment]
Hi @yzhzu , thanks for reporting this!  I will take a look at this tonight, but I think its an easy fix to the `setup.py` file...

**Comment by nickp60** [comment]
Hi @yzhzu, can you try again now?  It should install the latest tag (0.0.8) from pypi, which should resolve this...

**Comment by yzhzu** [comment]
Thank you very much Dear nickp60. it works

**Comment by nickp60** [comment]
Great! Keep me posted @yzhzu if you have any other issues, I know this repo could have better documentation!
